### ISSUE TITLE
Weird Attribute error when calling speadsheet via service account

### ISSUE THREAD

**Issue by DmitryBachin** [googleworkspace/python-samples#171]
## Expected Behavior
Making variable with access to the spreadsheet data
## Actual Behavior
```python
Traceback (most recent call last):
  File "/Users/dim/.local/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-b3f2c15efbc2>", line 1, in <module>
    runfile('/Users/dim/PycharmProjects/bioprocess_modelling/Bellossom/test.py', wdir='/Users/dim/PycharmProjects/bioprocess_modelling/Bellossom')
  File "/Users/dim/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-C/ch-0/201.8743.11/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/Users/dim/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-C/ch-0/201.8743.11/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/dim/PycharmProjects/bioprocess_modelling/Bellossom/test.py", line 15, in <module>
    range=range_name).execute()
  File "/Users/dim/opt/anaconda3/lib/python3.7/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Users/dim/opt/anaconda3/lib/python3.7/site-packages/googleapiclient/http.py", line 901, in execute
    headers=self.headers,
  File "/Users/dim/opt/anaconda3/lib/python3.7/site-packages/googleapiclient/http.py", line 177, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "/Users/dim/opt/anaconda3/lib/python3.7/site-packages/oauth2client/transport.py", line 159, in new_request
    credentials._refresh(orig_request_method)
  File "/Users/dim/opt/anaconda3/lib/python3.7/site-packages/oauth2client/client.py", line 749, in _refresh
    self._do_refresh_request(http)
  File "/Users/dim/opt/anaconda3/lib/python3.7/site-packages/oauth2client/client.py", line 774, in _do_refresh_request
    body = self._generate_refresh_request_body()
  File "/Users/dim/opt/anaconda3/lib/python3.7/site-packages/oauth2client/client.py", line 1484, in _generate_refresh_request_body
    assertion = self._generate_assertion()
  File "/Users/dim/opt/anaconda3/lib/python3.7/site-packages/oauth2client/service_account.py", line 385, in _generate_assertion
    key_id=self._private_key_id)
  File "/Users/dim/opt/anaconda3/lib/python3.7/site-packages/oauth2client/crypt.py", line 97, in make_signed_jwt
    signature = signer.sign(signing_input)
AttributeError: 'list' object has no attribute 'sign'
```

## Steps to Reproduce the Problem

```python
from googleapiclient.discovery import build
from oauth2client.service_account import ServiceAccountCredentials

scopes = ['https://www.googleapis.com/auth/spreadsheets',
          'https://www.googleapis.com/auth/drive']
spreadsheet_id = '1BfUXYVHOn-LWczAZroOzYQqliqm80jNCsh5zZxvR0Pk'
credentials_path = "/Users/dim/PycharmProjects/bioprocess_modelling/Bellossom/credentials.json"
range_name = 'Class equipment_list!A:Z'

credentials = ServiceAccountCredentials(credentials_path, scopes)

service = build('sheets', 'v4', credentials=credentials)
result = service.spreadsheets().values().get(
    spreadsheetId=spreadsheet_id,
    range=range_name).execute()
```

## Specifications

- Python 3.7.4
- macOS Catalina 10.15.2

**Comment by sqrrrl** [comment]
Use one of the class methods for creating the service accounts instead (it expects different args than what you're supplying.) See https://oauth2client.readthedocs.io/en/latest/source/oauth2client.service_account.html#oauth2client.service_account.ServiceAccountCredentials.from_json_keyfile_name
