### ISSUE TITLE
flow.run_local_server() raises AttributeError

### ISSUE THREAD

**Issue by mechanicalgirl** [googleworkspace/python-samples#193]
## Expected Behavior

Access a spreadsheet via Sheets API as described here: https://developers.google.com/sheets/api/quickstart/python#troubleshooting

## Actual Behavior

Running the code triggers an auth URL opening in a browser, and after going through the auth flow, attempts to redirect to a localhost path. Regardless of browser, the redirect fails on a connection error.

The stacktrace: 
```
Please visit this URL to authorize this application: https://accounts.google.com/o/oauth2/auth?response_type=code&client_id={redacted}&redirect_uri=http%3A%2F%2Flocalhost%3A19999%2F&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fspreadsheets.readonly&state={redacted}&access_type=offline
Traceback (most recent call last):
  File "sample.py", line 64, in <module>
    main()
  File "sample.py", line 41, in main
    creds = flow.run_local_server(port=19999)
  File "/Users/voxmedialoaner/Dropbox/My Mac (NYM-vox-media)/Desktop/VMG/voxmedia-repos/scripts/sheets/venv/lib/python3.8/site-packages/google_auth_oauthlib/flow.py", line 473, in run_local_server
    authorization_response = wsgi_app.last_request_uri.replace("http", "https")
AttributeError: 'NoneType' object has no attribute 'replace'
```

## Steps to Reproduce the Problem

1. Install requirements: `pip install --upgrade google-api-python-client google-auth-httplib2 google-auth-oauthlib`
1. Enable both the Sheets and Drive APIs in my GCP project
1. Run the script as defined here: https://developers.google.com/sheets/api/quickstart/python#step_3_set_up_the_sample

## Specifications

- Python 3.8.6
- Mac OS (Catalina)

## Additional notes

This appears to be a duplicate of the issue raised in https://github.com/googleworkspace/python-samples/issues/88 but it was never resolved. I've tried everything suggested in that thread - different browsers, default values for `success_message` and `port`. 

If there is a fix or a workaround, then either the [example code](https://developers.google.com/sheets/api/quickstart/python#step_3_set_up_the_sample) or the [troubleshooting section in the documentation](https://developers.google.com/sheets/api/quickstart/python#troubleshooting) needs to be updated.

**Comment by mechanicalgirl** [comment]
Working with the updated quickstart sample here results in the same behavior: https://github.com/googleworkspace/python-samples/blob/43fc5bceceddc8e6c8eb0e0917d4f5256ca604ca/sheets/quickstart/quickstart.py

**Comment by mechanicalgirl** [comment]
I'm probably going to move this over to the [google-auth-oauthlib](https://github.com/googleapis/google-auth-library-python-oauthlib) repo, that appears to be where the problem is originating.

The local_server appears to be starting up, but the `wsgi_app` (_RedirectWSGIApp) is not reliably returning a `last_request_uri`. For me, anyway, the wsgi app is getting [initialized](https://github.com/googleapis/google-auth-library-python-oauthlib/blob/53e31e2d03b315c12670370f67bdca29b1cd5422/google_auth_oauthlib/flow.py#L500-L507), but not [called](https://github.com/googleapis/google-auth-library-python-oauthlib/blob/53e31e2d03b315c12670370f67bdca29b1cd5422/google_auth_oauthlib/flow.py#L509-L522)
