### ISSUE TITLE
AttributeError: module 'google_auth_oauthlib' has no attribute 'helpers'

### ISSUE THREAD

**Issue by r96064013** [googleworkspace/python-samples#196]
## Steps to Reproduce the Problem

Step 1: Turn on the Google Calendar API
https://developers.google.com/calendar/quickstart/python#step_1_turn_on_the
Step 2: Install the Google Client Library
pip install --upgrade google-api-python-client google-auth-httplib2 google-auth-oauthlib
Step 3: Set up the sample
calendar/quickstart/quickstart.py
Step 4: Run the sample
Traceback (most recent call last):

  File "C:\Users\Chi-Yee\Desktop\Chi-Yee\google_calendar\python-samples-master\python-samples-master\calendar\quickstart\quickstart.py", line 75, in <module>
    main()

  File "C:\Users\Chi-Yee\Desktop\Chi-Yee\google_calendar\python-samples-master\python-samples-master\calendar\quickstart\quickstart.py", line 51, in main
    flow = InstalledAppFlow.from_client_secrets_file('credentials.json', SCOPES)

  File "C:\Users\Chi-Yee\anaconda3\lib\site-packages\google_auth_oauthlib\flow.py", line 183, in from_client_secrets_file
    return cls.from_client_config(client_config, scopes=scopes, **kwargs)

  File "C:\Users\Chi-Yee\anaconda3\lib\site-packages\google_auth_oauthlib\flow.py", line 159, in from_client_config
    google_auth_oauthlib.helpers.session_from_client_config(

**AttributeError: module 'google_auth_oauthlib' has no attribute 'helpers'**

## Specifications

- Python version (Python 3.8.3)
- OS (Windows 10 )

**Comment by alperezescudero** [comment]
Same problem here!

**Comment by hadzija7** [comment]
Did you solve this?
