### ISSUE TITLE
AttributeError: 'Credentials' object has no attribute 'to_json'

### ISSUE THREAD

**Issue by ced87** [googleworkspace/python-samples#213]
## Expected Behavior
create 'token.json' file and then print the next 10 calendar events, from quickstart.py, https://developers.google.com/calendar/api/quickstart/python.

## Actual Behavior
creates an empty 'token.json' with the following error:
```
Traceback (most recent call last):
  File "google_quickstart.py", line 69, in <module>
    main()
  File "google_quickstart.py", line 49, in main
    token.write(creds.to_json())
AttributeError: 'Credentials' object has no attribute 'to_json'
```
Then running again gives an error for an empty 'token.json'. I delete it to try again, but obviously same error as above.

## Steps to Reproduce the Problem

1. Use quickstart.py from https://developers.google.com/calendar/api/quickstart/python.
2. Used my 'credentials.json' file from the Google Cloud Platform.
3. Downloaded required pakckages.
4. Run in python.

## Specifications

- Python version 3.9.7.
- Windows 10 Pro Version 2004.

**Comment by ced87** [comment]
I started a fresh virtual environment. Issue solved.
